name: Deploy Palpittero BE to Production

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Production Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@master
      - name: Copy files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./*"
          target: /home/app/palpittero/palpittero-be/production
      - name: Install dependencies and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/app/palpittero/palpittero-be/production
            npm install
            cp /home/app/palpittero/palpittero-be/.env.production /home/app/palpittero/palpittero-be/production/.env.production
            npm run db:migrate
            pm2 restart palpittero-api-production
