name: Deploy Palpittero BE to Staging

on: 
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploying to Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/setup-node@master
      - name: Copy files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./*"
          target: /home/app/palpittero/palpittero-be/staging
      - name: Install dependencies and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker exec palpittero-be-mysql /bin/bash -c 'exec mysqldump --databases palpittero-staging -uroot -p"$MYSQL_ROOT_PASSWORD"' > /root/backup/palpittero-staging_$(date +"%Y-%m-%d-%H-%M").sql
            cd /home/app/palpittero/palpittero-be/staging
            npm install
            cp /home/app/palpittero/palpittero-be/.env.staging /home/app/palpittero/palpittero-be/staging/.env.staging
            npm run db:migrate:staging
            pm2 restart palpittero-api-staging
